In [23]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [24]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [25]:
type(list_)

list

In [26]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [27]:
def data_type_list(n):
    for i in n:
        print(type(i), end = ',')

In [12]:
data_type_list(list_)

<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,

In [28]:
np.array([type(i) for i in array_list])

array([<class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>,
       <class 'numpy.str_'>, <class 'numpy.str_'>], dtype=object)

Q3. Considering the following changes in the variable, array_list:

In [29]:
array_list = np.array(object = list_, dtype = int)

In [30]:
# Changes will only be happened in array_list not list_

In [31]:
data_type_list(list_)

<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,

In [33]:
data_type_list(array_list)

<class 'numpy.int64'>,<class 'numpy.int64'>,<class 'numpy.int64'>,<class 'numpy.int64'>,<class 'numpy.int64'>,

In [34]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [37]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
num_array.shape

(2, 3)

In [40]:
num_array.size

6

In [44]:
arr = np.zeros(9)

In [45]:
arr.reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
arr1 = np.eye(5)

In [49]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])